### ISSUE TITLE
Home Module

### ISSUE THREAD

**Issue by dcabungcal** [dcabungcal/storebot#2]
Function Code : SBF_002
Details:
The Home page is the main page after user is verified, this will show all the options and functions available for the application.

Action Plan:
- [ ]  Create Home UI #15 
- [ ] Implement Home Backend #16 
- [ ] Create Home Testcase #13 
- [ ] Perform Home Test #18 

Acceptance Criteria:
